<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAfBKx2k\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAfBKx2k/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerAfBKx2k.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerAfBKx2k\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerAfBKx2k\appAppKernelProdContainer([
    'container.build_hash' => 'AfBKx2k',
    'container.build_id' => '608f0256',
    'container.build_time' => 1675948776,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAfBKx2k');
